version: '3'

services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./dev-env/mysql:/var/lib/mysql
            - ./dev-env/dumps:/dumps
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress

    wordpress:
        depends_on:
            - mysql
        build: .
        volumes:
            - ./dev-env/wordpress:/var/www/html
            - ./landtalk-custom-theme:/var/www/html/wp-content/themes/landtalk-custom-theme
        ports:
            - "80:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
volumes:
    db_data: